version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb-data:/data/db

  frontend:
    image: frontend
    build: frontend
    volumes:
      - frontend-dist:/app/dist

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx_balancer/nginx.conf:/etc/nginx/nginx.conf
      - frontend-dist:/var/www/app/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - scala1
      - scala2
      - frontend

  scala1:
    image: scala
    build: scala
    depends_on:
      - mongodb
    environment:
      MONGO_CONNECTION_URI: "mongodb://mongodb:27017"

  scala2:
    image: scala
    build: scala
    depends_on:
      - mongodb
    environment:
      MONGO_CONNECTION_URI: "mongodb://mongodb:27017"

volumes:
  mongodb-data:
  frontend-dist:
