version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
    networks:
      - backend

  frontend:
    build: ../frontend
    volumes:
      - ../frontend/dist:/app/dist

  nginx:
    image: nginx
    restart: always
    volumes:
      - ../nginx_balancer/nginx.conf:/etc/nginx/nginx.conf
      - ../frontend/dist:/var/www/app/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    depends_on:
      - scala1
      - scala2
      - frontend

  scala1:
    build: ../scala
    networks:
      - backend
    depends_on:
      - mongodb

  scala2:
    build: ../scala
    networks:
      - backend
    depends_on:
      - mongodb

networks:
  backend:

volumes:
  mongodb-data: