version: '3'
services:
  webapp1:
    image: mywebapp
    ports:
      - "5000"
  webapp2:
    image: mywebapp
    ports:
      - "5000"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webapp1
      - webapp2